version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node:
          steps:
            - run: npm install
            - run: npm test
  build-and-test2:
    executor:
      name: node/default
    steps:
      - checkout
      - node:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - build-and-test2
